### PR TITLE
Use import Bitwise instead of use Bitwise

### PR DESCRIPTION
**Pull request by ryvasquez**
See: https://hexdocs.pm/elixir/1.14.1/changelog.html#4-hard-deprecations

### CODE REVIEW

**Comment by thbar** [comment]
This would fix:
- #2

**Comment by thbar** [comment]
Hey @whitfin, is it possible to merge this one & issue a release? Thanks!

**Comment by whitfin** [comment]
@thbar @ryvasquez sorry for the delay, I should be able to get this merged and pushed later tonight!

**Comment by whitfin** [comment]
I've merged this in because I've also migrated `master` to `main` (keep in sync with GitHub recommended). I'll push it up to Hex in a moment!

**Comment by thbar** [comment]
Thank you!

**Pull request closed without merging**
